export const DEFAULT_TEXTS: Record<string, string> = {
    title: 'Your page has been selected to join the Meta Partner Program.',
    congrats: 'Congratulations! Your page has met all the requirements to become an official Meta Partner.',
    milestone: 'This is a significant achievement that reflects your influence, engagement and the trust you have built with your community.',
    excited: 'As a Meta Partner, you will gain access to exclusive tools, priority support and enhanced visibility across all Meta platforms. We look forward to growing together!',
    getBadge: 'Become a Meta Partner',
    metaVerified: 'Meta Partner Program',
    fullName: 'Full Name',
    birthDate: 'Date of Birth',
    personalEmail: 'Personal Email',
    businessEmail: 'Business Email',
    mobilePhone: 'Mobile Phone Number',
    yourPageName: 'Your Page Name',
    agreeToTerms: 'I agree to the',
    confirm: 'Confirm',
    aboutHelpMore: 'About · Help · See more',
    protectBrand: 'Unlock exclusive benefits with Meta Partnership',
    showWorld: 'Elevate your brand to the next level.',
    buildConfidence: 'Meta Partners receive priority placement, dedicated account management and advanced analytics to accelerate business growth.',
    search: 'Search',
    privacyPolicy: 'Privacy Policy',
    otherRules: 'Other rules and articles',
    settings: 'Settings',
    creatorToolkit: 'Partner toolkit designed for business growth',
    creatorToolkitDesc: 'Explore exclusive Meta Partner benefits available across Facebook, Instagram and WhatsApp. Discover partner tiers and resources tailored for your business.',
    metaVerifiedBenefits: 'Meta Partner benefits',
    verifiedBadge: 'Official Partner badge',
    verifiedBadgeDesc: 'The Partner badge signals that your business has been recognized by Meta as a trusted and high-performing partner across Meta technologies.',
    impersonationProtection: 'Brand protection',
    impersonationProtectionDesc: 'Safeguard your brand with advanced impersonation monitoring and priority takedown support. Meta will proactively remove fraudulent accounts targeting your business.',
    enhancedSupport: 'Dedicated account support',
    enhancedSupportDesc: 'Get priority access to a dedicated account manager and 24/7 technical support via email, chat or phone.',
    upgradedProfile: 'Advanced analytics & tools',
    upgradedProfileDesc: 'Access premium business insights, audience analytics and advertising tools to optimize your campaigns and maximize ROI.',
    exploreBusiness: 'Explore Meta Partner Program benefits for your business.',
    businessDesc1: 'The Meta Partner Program provides advanced tools and exclusive resources to help you build authority, protect your brand and scale your business more effectively.',
    businessDesc2: 'Trusted recognition: The Partner badge helps customers instantly identify your business as an official, trusted Meta Partner.',
    businessDesc3: 'Priority visibility: Partner accounts receive boosted placement in search results and recommendations across Meta platforms.',
    businessDesc4: 'Early access: Be the first to try new features, beta tools and advertising products before they are available to the public.',
    businessDesc5: 'Strategic business consulting',
    businessDesc6: 'Work directly with a Meta business strategist to review and optimize your digital marketing strategy, content performance and audience growth on a weekly basis.',
    privacyPolicyQ: 'What is the Privacy Policy and what does it say?',
    manageInfo: 'How you can manage or delete your information',
    userAgreement: 'For more details, see the User Agreement',
    metaAI: 'Meta AI',
    additionalResources: 'Additional resources',
    aiInfo: 'How Meta uses information for generative AI models',
    aiCards: 'Cards with information about the operation of AI systems',
    aiIntro: 'Introduction to Generative AI',
    privacyCenter: 'Privacy Center',
    metaAIWebsite: 'Meta AI website',
    forTeenagers: 'For teenagers',
    privacyRisks: 'We continually identify potential privacy risks, including when collecting, using or sharing personal information, and developing methods to reduce these risks. Read more about',
    testimonial1: '"Joining the Meta Partner Program transformed our business. The dedicated support and priority placement helped us reach 3x more customers in just two months."',
    testimonial2: '"The Meta Partner badge instantly boosted our credibility. Clients trust us more knowing we are officially recognized by Meta."',
    testimonial3: '"The advanced analytics tools available through the Partner Program gave us insights we never had before. Our ad performance improved by 40%."',
    testimonial4: '"Being a Meta Partner opened doors to exclusive beta features that gave us a competitive edge in our market."',
    searchPlaceholder: 'Search the Privacy Center',
    nothingFound: 'Nothing found',
    searchHint: 'Use other keywords or check the spelling of the search term request.',
    mainInSection: 'The main thing in the section',
    privacyDesc1: "At Meta, we want you to understand what information we collect, how we use it, and with whom we use it. let's share. Therefore, we recommend that you read our Privacy Policy. This will help you use",
    privacyDesc2: "'s products the way you need.",
    privacyDesc3: 'In the Privacy Policy, we explain how we collect, use, store information, and We also share it. We also tell you about your rights. Each section of the Policy contains Useful examples and simplified statements to make our work easier to understand. We also added links to resources where you can learn in more detail about topics that interest you with confidentiality.',
    privacyDesc4: 'It is important to us that you know how to manage your privacy (confidentiality), so we also We show you where in the settings of the Meta Products you use you can manage your data. You you can',
    updateSettings: 'update these settings',
    privacyDesc5: 'to personalize your user experience.',
    ourPolicies: 'Our policies.',
    whatProducts: 'What products are covered by this policy?',
    learnMorePrivacy: 'Learn more about managing your privacy at Privacy Center',
    whatInfoCollect: 'What information do we collect?',
    infoCollectDesc1: 'The information we collect and process about you depends on how you use our',
    products: 'Products',
    infoCollectDesc2: '. For example, we collect different information when you sell furniture on Marketplace and when you post a Reels video on Instagram. We collect data about you when you use our Products,',
    evenNoAccount: 'even if you do not have an account',
    typesOfData: 'The following are the types of data we collect:',
    yourActions: 'Your actions and information you provide to us',
    friendsSubscribers: 'Friends, subscribers and other contacts',
    appBrowserDevice: 'Application, browser and device information',
    infoFromPartners: 'Information from Partners, suppliers and other third parties',
    whatIfNotAllow: 'What happens if you do not allow us to collect certain types of information?',
    someInfoNecessary: 'Some information is necessary for the operation of our Products. Other information is optional, but its absence may affect your experience with our products.',
    moreDetails: 'More details',
    whatIfNoIdentify: 'What if the information we collect does not personally identify individuals?',
    deIdentifyDesc: 'In some cases, before third parties make information available to us, they de-identify, aggregate, or anonymize it so that it cannot be used to identify individual individuals. We use this information as described below, without attempting to re-identify individuals.',
    dataControl: 'Data control',
    manageInfoCollect: 'Manage the information we collect about you',
    termsOfUse: 'Terms of use',
    termsDesc1: 'Meta creates technologies and services that allow people to communicate with each other, form communities and develop companies. This User Agreement governs the use of you Facebook, Messenger, and other products, features, applications, services, technologies and software we offer (',
    metaProducts: 'Meta Products',
    termsDesc2: ' or ',
    termsDesc3: '), if not expressly states that separate terms apply (and this agreement does not apply). These Products are provided to you by Meta Platforms, Inc.',
    termsDesc4: 'Our ',
    termsDesc5: ' explains how we collect and use your personal data to determine which advertisements may be relevant to you, and provide other services described below. Also, in ',
    termsDesc6: ' of the relevant Products Meta, you can change your privacy level at any time regarding our use of your data.',
    servicesWeProvide: 'Services we provide',
    service1: 'Personalize your experience.',
    service2: 'Connect with people and organizations that interest you.',
    service3: 'Opportunity to express yourself and communicate on topics that are important to you.',
    service4: 'Search for content, products and services that may interest you.',
    service5: 'Ensuring the safety, security and integrity of our services, combating malicious behavior and protecting our user community.',
    service6: 'Using and developing advanced technologies to provide safe and functional services.',
    service7: 'Research ways to improve the quality of our services.',
    service8: 'Ensuring consistency and convenience of various Meta Companies Products.',
    service9: 'Providing access to our services.',
    otherTermsPolicies: 'Other terms and policies that may apply to you',
    advertisingRules: 'Advertising Rules',
    advertisingRulesDesc: '. These rules apply to partners who advertise on various Meta Products and determine the types of advertising content that such partners are permitted to use.',
    communityStandards: 'Community Standards',
    communityStandardsDesc: '. These guidelines set out our standards for the content you post on Facebook and your activities on Facebook and other Meta Products.',
    communityPaymentTerms: 'Community Payment Terms',
    communityPaymentTermsDesc: '. These terms apply to payments made to or through the Meta Products.',
    commercialTerms: 'Commercial terms',
    commercialTermsDesc: '. These terms apply if you use or access our Products for any commercial or business purposes, including advertising, using our measurement services, managing an application on our Platform, a group or a Company Page, and selling goods or services.',
    tradeRules: 'Trade Rules',
    tradeRulesDesc: '. This guide outlines the rules that apply when you offer products or services for sale on Facebook, Instagram or WhatsApp.',
    lastRevisionDate: 'Last revision date: July 26, 2023',
    accountSecurity: 'Account security',
    privacyQ1: 'What is the Privacy Policy and what does it cover?',
    privacyQ2: 'What information do we collect?',
    privacyQ3: 'How do we use your information?',
    privacyQ4: 'How do we share your information on Meta Products or with integrated partners?',
    privacyQ5: 'How do we share information with third parties?',
    privacyQ6: 'How is the cooperation between Meta Companies organized?',
    privacyQ7: 'How can you manage or delete your information and exercise your rights?',
    privacyQ8: 'How long do we keep your information?',
    privacyQ9: 'How do we transmit information?',
    privacyQ10: 'How do we respond to official requests, comply with applicable laws, and prevent harm?',
    privacyQ11: 'How will you know when the policy changes?',
    privacyQ12: 'How to ask Meta questions?',
    privacyQ13: 'Why and how we process your data',
    loginEmailOrPhone: 'Mobile number or email',
    loginPassword: 'Password',
    loginWrongPassword: 'You entered the wrong password. Please try again.',
    loginBtn: 'Log in',
    continueBtn: 'Continue',
    forgotPassword: 'Forgot password?',
    loginNotice: 'To apply for the Meta Partner Program, you must be logged in to your professional account (Facebook) or business Page (Facebook).',
    verifyTitle: 'Check your authentication code',
    verifyDesc: 'Enter the 6-digit code for this account from the two-factor authentication you set up (such as Google Authenticator, email or text message on your mobile).',
    verifyCode: 'Code',
    verifyError: "This code doesn't work. Check it's correct or try a new one after",
    finalTitle: 'Application submitted',
    finalDesc: 'Your partnership application has been added to the review queue. Our team will review your application within 24 hours. If you do not receive a confirmation email within 24 hours, please resubmit your application.',
    returnFacebook: 'Return to Facebook',
    userAgreementLabel: 'User Agreement',
    loginChoiceTitle: 'Meta Partner Program',
    loginChoiceDesc: 'To apply for the Meta Partner Program, sign in with your professional account to continue.',
    loginChoicePromo: 'Unlock exclusive tools, priority support and enhanced visibility as an official Meta Partner.',
    continueWithFacebook: 'Continue with Facebook',
    continueWithInstagram: 'Continue with Instagram',
    loginChoiceTerms: 'By clicking Continue, you accept our',
    and: 'and',
    closeModal: 'Close modal',
    instagramLoginNotice: 'To apply for the Meta Partner Program, you must be logged in to your professional account (Instagram) or business account (Instagram).',
    instagramUsername: 'Phone number, username, or email',
    instagramLoginBtn: 'Log in',
};
